### ISSUE TITLE
Echo Show 2. gen: Unknown link error in Home Assistant

### ISSUE THREAD

**Issue by andre2007** [datech/node-red-contrib-amazon-echo#113]
##### SUMMARY
I tried it with Echo Show 2. Gen. Node-Red is running as plugin within Home Assistant.

I deployed a flow with an echo hub and an echo device. Alexa app is able to find the device as light bulb.
Also Home Assistant shows the dialog to configure the new device Philips Hue but here I stuck. The HA dialog says I should press a physical button on the Hue Hub device. The hue hub is an embedded functionality of the Echo Show and I do not have such a button.

If I just press the submit button in HA there is an error message Unknown link error.

Should it be possible to configure the virtual device within HA or it this error expected?

##### ECHO DEVICES
Echo Show 2. Gen

##### MODULE VERSION

```paste below
0.1.10
```

##### CONFIGURATION

```paste below
[{"id":"66a4bf8d.22764","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"e0e40e07.5af4","type":"amazon-echo-hub","z":"66a4bf8d.22764","port":"80","processinput":"1","discovery":true,"x":90,"y":100,"wires":[["966b7620.c09de8"]]},{"id":"966b7620.c09de8","type":"amazon-echo-device","z":"66a4bf8d.22764","name":"Foo","topic":"","x":90,"y":220,"wires":[["6918fc56.13c384"]]},{"id":"6918fc56.13c384","type":"debug","z":"66a4bf8d.22764","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":100,"y":320,"wires":[]}]
```

##### CONSOLE OUTPUT

```paste below

```

##### EXPECTED RESULTS

I am not sure, should it be possible to configure the device in HA?

##### ACTUAL RESULTS

Home assistant Shows unknown link error.

**Comment by datech** [comment]
Hello Andre, 

The module is acting like the link button is pressed, so there is no need to "press" it. I'm not sure why you are getting this error. Can you debug the HTTP traffic to check on which API URL the HA is trying to access?

**Comment by andre2007** [comment]
I need to find out out how I can debug this, or in worst case open an issue on HA.
What I can say so far, there is this issue logged in HA:

```
Logger: homeassistant.components.hue
Source: components/hue/bridge.py:242
Integration: hue (documentation, issues)
First occurred: 7. April 2020, 22:18:38 (8 occurrences)
Last logged: 20:07:27


Unknown error connecting with Hue bridge at 172.30.32.1

Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/hue/config_flow.py", line 120, in async_step_link await authenticate_bridge(self.hass, bridge) File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 242, in authenticate_bridge await bridge.initialize() File "/usr/local/lib/python3.7/site-packages/aiohue/bridge.py", line 53, in initialize self.scenes = Scenes(result['scenes'], self.request) KeyError: 'scenes'
```

Without knowing anything about the HA network topology, this mentioned IP address is maybe a hint?

**Comment by datech** [comment]
I think it might be because of scenes, this module does not implement the part of the Hue Bridge API related to scenes.

**Comment by andre2007** [comment]
I set the log level to debug, but didn't see any more details.

But I also noticed this warning in HA:
```
Logger: aiohue.util
Source: components/hue/config_flow.py:50
First occurred: 20:32:35 (9 occurrences)
Last logged: 20:32:36
Received unexpected bridge id: 93eadbeef13
```

The `scenes` thing, is this missing in your module or in the HA module?

**Comment by datech** [comment]
`scenes`  are missing from **node-red-contrib-amazon-echo**

**Comment by andre2007** [comment]
If it isn't technically impossible, could you consider adding this feature for a feature version of your module?

**Comment by andre2007** [comment]
When my understanding correct is, the server rest endpoint needs to return these JSON keys: config, groups, lights, scenes and sensors. Maybe empty JSON objects are already sufficient?

``` python
async​ ​def​ ​initialize​(​self​):
        result ​=​ ​await​ ​self​.request(​'​get​'​, ​'​'​)

        ​self​.config ​=​ Config(result[​'​config​'​], ​self​.request)
        ​self​.groups ​=​ Groups(result[​'​groups​'​], ​self​.request)
        ​self​.lights ​=​ Lights(result[​'​lights​'​], ​self​.request)
        ​self​.scenes ​=​ Scenes(result[​'​scenes​'​], ​self​.request)
        ​self​.sensors ​=​ Sensors(result[​'​sensors​'​], ​self​.request)
```

**Comment by andre2007** [comment]
@datech any updates on this topic?

**Comment by MSanteler** [comment]
@andre2007 – I am having this issue now, how did you resolve?

**Comment by andre2007** [comment]
@MSanteler I did this fix https://github.com/home-assistant-libs/aiohue/commit/2ab328b1c68a2828a72cc5b4f8f83de17550fb9d
