### ISSUE TITLE
Docker EACCES permission denied

### ISSUE THREAD

**Issue by purebenwoo** [datech/node-red-contrib-amazon-echo#24]
##### SUMMARY

I'm running Node-RED in a docker container. Everything else works fine. I've even used the contrib-alexa-local palette with no problems. The nodered container is running as root (`--user 0`, and also tried `--user root`). I'm using `--network host` (also tried `--net=host`). I'm still getting the Error: listen EACCES: permission denied 0.0.0.0:80.

I've tried the iptables settings on the host system (i.e. outside the container), the Node RED container doesn't have iptables installed.

##### ECHO DEVICES

2x Echo Dot 2nd generation
1x Echo Dot 3rd generation

##### MODULE VERSION

```paste below
0.1.8
```

##### CONFIGURATION

```paste below
![image](https://user-images.githubusercontent.com/45885373/52917323-e2096980-329e-11e9-93da-4a50eef2b9d0.png)

Not sure if the image is showing, but basically, I've just got the Amazon Echo Hub, and under it is a red warning stating Unable to start on port 80
```

##### CONSOLE OUTPUT

```paste below
17 Feb 18:27:55 - [info] Starting flows
17 Feb 18:27:57 - [info] Started flows
17 Feb 18:27:57 - [error] Error: listen EADDRINUSE :::80
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at new AmazonEchoHubNode (/data/node_modules/node-red-contrib-amazon-echo/index.js:47:20)
    at createNode (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
    at Flow.start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:89:35)
    at start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)
    at tryCatchReject (/usr/src/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/src/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/src/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/src/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/src/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/src/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

```

##### STEPS TO REPRODUCE

Not much to describe

**Comment by Barabba11** [comment]
Using root rights on node red produces unexpected and indesiderabile results. Avoid it. I suggest you install all again with no root.
Port mapping as described some times around here works simply perfect. I suggest you to use wha alreadyt people guarantee it's working, and not experiment yourself, save your time! )

**Comment by purebenwoo** [comment]
Hmm... OK, will try without root. Will report results.

**Comment by purebenwoo** [comment]
It works. Thanks @Barabba11
