### ISSUE TITLE
Hub does not work with current NodeRed

### ISSUE THREAD

**Issue by mglaeske** [datech/node-red-contrib-amazon-echo#91]
##### SUMMARY

After inserting the Node and running the device recognition from Echo, the only thing you can see is a stacktrace in debug output.
I have fixed the problem for me in your code "node-red-contrib-amazon-echo/index.js":
```
 function getOrDefault(key, defaultValue, context) {    
                                              
    var value = null;                                                                       
    var storageValue = undefined;                  
    if (key !== undefined) {                   
       storageValue = context.get(key);                                               
    }                                             
                                                                                                                
    // Clone value                                                                                   
    if (storageValue !== undefined) {               
      value = Object.assign({}, storageValue);                                                    
    }                                                                                                           
                                                
    return valueOrDefault(value, defaultValue);                             
  } 
```

##### ECHO DEVICES

Echo 2nd generation ... but that is not the problem.

##### MODULE VERSION

```paste below
0.1.9
```

##### CONFIGURATION

```paste below
[{"id":"8fd067d4.b88118","type":"amazon-echo-hub","z":"c1b035b4.2836d8","port":"80","processinput":0,"x":140,"y":180,"wires":[["7fec4c4b.5fd3c4"]]},{"id":"7fec4c4b.5fd3c4","type":"amazon-echo-device","z":"c1b035b4.2836d8","name":"test2","topic":"test2","x":350,"y":180,"wires":[["8a3573a.544ba9"]]}]
```

##### CONSOLE OUTPUT

```paste below
TypeError: Cannot read property 'startsWith' of undefined
    at followParentContext (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js:207:18)
    at Object.value (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js:275:34)
    at getOrDefault (/data/node_modules/node-red-contrib-amazon-echo/index.js:314:31)
    at getDeviceAttributes (/data/node_modules/node-red-contrib-amazon-echo/index.js:376:12)
    at getDevicesAttributes (/data/node_modules/node-red-contrib-amazon-echo/index.js:385:24)
    at /data/node_modules/node-red-contrib-amazon-echo/index.js:205:17
    at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/data/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
    at /data/node_modules/express/lib/router/index.js:281:22
    at param (/data/node_modules/express/lib/router/index.js:354:14)
    at param (/data/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/data/node_modules/express/lib/router/index.js:410:3)
    at next (/data/node_modules/express/lib/router/index.js:275:10)
    at /data/node_modules/node-red-contrib-amazon-echo/index.js:169:7
```

**Comment by datech** [comment]
Can you share more details about Node-RED and Node.js versions?

**Comment by datech** [comment]
Feel free to reopen the issue if you didn't manage to resolve it.
